Repository betaflight/config, pull requests merged in 2025-08, with the labels that each got.

#845 Add UART 7 and 8 to AXISFLYINGF745AIO
  configs/AXISFLYINGF745AIO/config.h
Labels: Bugfix

#847 Add HSE to JHEG474
  configs/JHEG474/config.h
Labels: Bugfix

#851 HELLBENDER_0001 - Adding LED STRIP PIN
  configs/HELLBENDER_0001/config.h
Labels: Housekeeping

#850 SUPPORT: Adding detail on targets that are supported
  configs/SPEDIXG473/config.h
Labels: Housekeeping

#861 Correct manufacturer Id for JHEG474
  configs/CHONKERH735/config.h
  configs/HGLRCF405V2/config.h
  configs/JHEG474/config.h
Labels: Bugfix

#863 Update missing manufacturers
  Manufacturers.md
Labels: New manufacturer, Housekeeping

#886 Remove redefined mag_i2c_instance BETAFPVF405
  configs/BETAFPVF405/config.h
Labels: Bugfix
